import os

from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Demo Project
    Package: TestProject.Generated.Tests.DemoProject
    Test: AirBnb Test
    Generated by: Ran Tzur (rantzrur@gmail.com)
    Generated on 04/07/2021, 11:02:07
"""


@pytest.fixture()
def driver():
    os.environ["TP_AGENT_URL"] = "http://localhost:8787"
    driver = webdriver.Firefox(token="MSlM0L0EXHkqZ0CLf98m9Qn4YRcBoPaaxsMEDsH6FrQ1",
                              project_name="Demo Project",
                              job_name="AirBnb Test")
    step_settings = StepSettings(timeout=15000, screenshot_condition=TakeScreenshotConditionType.Failure)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.airbnb.com"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'query'
    query = driver.find_element(By.CSS_SELECTOR,
                                "#bigsearch-query-detached-query")
    query.click()

    # 3. Type 'Hawaii' in 'query'
    query = driver.find_element(By.CSS_SELECTOR,
                                "#bigsearch-query-detached-query")
    query.send_keys("Hawaii")

    # 4. Click 'Add dates'
    add_dates = driver.find_element(By.XPATH,
                                    "//div[1]/div/div/div[. = 'Add dates']")
    add_dates.click()

    # 5. Click '20'
    _20 = driver.find_element(By.XPATH,
                              "//td[3]/div/div/div[. = '20']")
    _20.click()

    # 6. Click '231'
    _231 = driver.find_element(By.XPATH,
                               "//td[6]/div/div[. = '23']")
    _231.click()

    # 7. Click 'Add guests'
    add_guests = driver.find_element(By.XPATH,
                                     "//div[. = 'Add guests']")
    add_guests.click()

    # 8. Click 'BUTTON'
    button = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/button[2]")
    button.click()

    # 9. Click 'BUTTON1'
    button1 = driver.find_element(By.XPATH,
                                  "//div[1]/div[2]/button[2]")
    button1.click()

    # 10. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//button/span/span")
    span.click()

    # 11. Get text from 'Stays in Hawaii'
    stays_in_hawaii = driver.find_element(By.XPATH,
                                          "//h1[. = 'Stays in Hawaii']")
    step_output = stays_in_hawaii.text
    assert "Hawaii" in step_output
